### ISSUE TITLE
Erro - Primeira Parte da Oficina 

### ISSUE THREAD

**Issue by naiaralarsen** [Introducao-ao-R-na-Abraji/oficina-R#1]
Oi, gente!

Estou com dificuldades na primeira parte da oficina, não estou conseguindo rodar os comandos. Intuo que seja porque não consegui baixar todos os pacotes mas não tenho certeza se é isso mesmo.  

O que aparece depois que tento baixar os pacotes:

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

É problema mesmo com os pacotes, como faço para consertar isso?

Obrigada.

**Comment by gabrielacaesar** [comment]
Oi, Naiara. Tudo bem?

Após baixar o R, você também instalou na sua máquina? Qualquer coisa o passo a passo para a instalação do R e do RStudio está [aqui](https://www.curso-de-programacao-em-r-para-jornalistas.com/2019/10/27/instalacao-r-e-rstudio/).

Se tiver instalado, eu vi que alguns usuários também relataram esse problema. Acho que essas perguntas do StackOverflow/fórum de dúvidas podem te ajudar. Dê uma olhada [aqui](https://stackoverflow.com/questions/19885381/rtools-not-being-detected-by-r) e [aqui](https://www.it-swarm.dev/pt/windows/rtools-nao-sendo-detectado-por-r/1043078505/).

Às vezes o console mostra alguns avisos/alertas ao instalar os pacotes, mas isso não impede o pacote de funcionar. Dê uma olhada para ver se as funções estão funcionando normalmente.

Depois, por favor, avise-nos se você conseguiu resolver o problema ou se o console mostrou outro erro. Estamos aqui para ajudá-la. :)

**Comment by naiaralarsen** [comment]
Oi, Gabriela. 

Obrigada pelo retorno! A principio consegui, instalei os programas em outra máquina e deram o mesmo erro mais daí como apontavam um url para baixar, essa: 

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/abjutils_0.3.1.zip'
Content type 'application/zip' length 75775 bytes (73 KB)
downloaded 73 KB

Copiei, colei e baixei. Parece que deu certo. Ah, e também não busquei o arquivo pelo File, como tinha feito na vez anterior, rodei direto pelo que voce deixou no programa. 

```{r}
# df_pensionistas_07_2020 <- fread("data/PENSIONISTAS_072020.csv")
df_pensionistas_07_2020 <- readRDS("data/julho2020.rds")
```
Ai consegui rodar também as funções seguintes, que antes não tinha conseguido fazer a verificação igual você mostrava no vídeo. 

Enfim, acho que deu certo, rumo a segunda aula. 

Obrigada, oficina excelente. ;)

**Comment by gabrielacaesar** [comment]
Maravilha, Naiara! Qualquer coisa é só falar :)
